name: Ansible Image Build
on:
  push:
    branches: ["master"]
    paths:
      - "builds/ansible/**"
  schedule:
    - cron: 10 0 1 * *
  workflow_dispatch:

env:
  DIR: builds/ansible

jobs:
  build:
    name: Build ansible container
    runs-on: self-hosted
    if: contains( github.ref, 'master')

    steps:
      - name: Log into ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout git repo
        uses: actions/checkout@v2

      - name: Packer validate
        run: packer validate -var-file ${{ env.DIR }}/packer.auto.pkrvars.hcl ${{ env.DIR }}/packer.pkr.hcl

      - name: Packer build
        run: packer build -var-file ${{ env.DIR }}/packer.auto.pkrvars.hcl ${{ env.DIR }}/packer.pkr.hcl
