name: Test self-hosted runner
on:
  workflow_dispatch:

jobs:
  build:
    name: Test self-hosted runner
    runs-on: self-hosted

    steps:
      - name: Test runner
        run: docker run --rm hello-world
