name: Test self-hosted runner
on:
  workflow_dispatch:

jobs:
  build:
    name: Test self-hosted runner
    runs-on: self-hosted
#    container:
#      image: alpine
      
    steps:
#      - name: Output something
#        run: cat /etc/os-release
      - name: Output something
        run: docker run --rm -d alpine cat /etc/os-release
