name: Test self-hosted runner
on:
  workflow_dispatch:

jobs:
  build:
    name: Test self-hosted runner
    runs-on: self-hosted
    container:
      image: busybox
      
    steps:
      - name: Output something
        run: busybox | head -1
